student_arr = [
"Brooke	Ryan",
"Ashe Austaire",
"Diego Dorado",
"Sikander Chowhan",
"David Squires",
"Ian Ramos",
"Elbin Keeppanasseril",
"David Goodman",
"Matthew Gellert",
"Matthew Lawford",
"Anna Bush",
"David Tannenbaum",
"Ryan Sperzel",
"Al Artesona",
"William Scripps",
"Christina Pan",
"Ian Shaw",
"Natalie Deal",
"Jon Openshaw",
"Danielle Bennet",
"Lisa Hufnagel",
"Cole Shapiro"
]
